### PR TITLE
Fix #50 - Added support for boolean PGType

### LINKED ISSUE #50: PGCommand BOOLEAN parameter
Hi,
I use ddb my vibe.d project and I run below code getting error?

```
PGCommand` cmd = new PGCommand(mConn);
cmd.query = "UPDATE test SET status = $1 WHERE id = $2";
cmd.parameters.add(1, PGType.BOOLEAN).value = true;
cmd.parameters.add(2, PGType.INT4).value = 105;
cmd.executeNonQuery();
``
```

### PR DESCRIPTION
**Pull request by Bishop92**
Also added the type of the param not supported when asserting.

### CODE REVIEW

**Comment by jacob-carlborg** [comment]
Is this a fix for this issue https://github.com/pszturmaj/ddb/issues/50?

**Comment by pinver** [comment]
It seems so...

**Comment by Bishop92** [comment]
Yes, this fix #50

**Comment by jacob-carlborg** [comment]
If you prefix the commit message with `Fix #50` it will automatically close the issue.

**Comment by jacob-carlborg** [comment]
@zafer06 @claudiug does this fix issue #50 for you?

**Comment by zafer06** [comment]
Yes, I do. Thank you @Bishop92  and @jacob-carlborg.

**Comment by jacob-carlborg** [comment]
@Bishop92 if you update the commit message I can merge this.

**Comment by Bishop92** [comment]
It's ok now?

**Comment by jacob-carlborg** [comment]
> It's ok now?

Unfortunately no because now there are three commits. Please squash them.

**Comment by Bishop92** [comment]
Ok I've squashed the commits!

**Comment by jacob-carlborg** [comment]
* Looks like something happened with the commit message
* Did you add new code? Like https://github.com/pszturmaj/ddb/pull/66/files#diff-7ff5c91ca3bf275ef694b8d7094fd4f3R1295

**Comment by Bishop92** [comment]
Seems that something went wrong when I've squashed the commits. I close this pull request and make another one clean.

**Pull request closed without merging**
